image:
  file: .gitpod.dockerfile
tasks:
  - init: lein deps
    command: mkdir .shadow-cljs; echo 5555 > .shadow-cljs/socket-repl.port; lein repl

vscode:
  extensions:
    - mauricioszabo.clover@0.0.4:MHmP3EBKs6lGCDNEAeixVg==
    - mauricioszabo.clover@0.1.0:inIzqdXr7mgwxUmMTO7rCg==